spring:
  datasource:
    url: jdbc:sqlserver://shubhamsql.database.windows.net:1433;database=shubhamsql;user=shubhamsql@shubhamsql;password=Password@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: shubhamsql
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
      database-platform: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


